# Generated by Django 4.0.7 on 2022-09-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=255)),
                ('is_accessible', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('update_date', models.DateTimeField()),
            ],
        ),
    ]
