# Generated by Django 3.2 on 2022-09-21 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectivity', '0002_alter_connectivity_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 13, 55, 24, 110301)),
        ),
    ]
